global:
  message: Welcome to order service in dev environment!
server:
  port: 8082
message: Hello from Dev environment!
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/order_dev
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
