global:
  message: Welcome to order service in prod environment!
server:
  port: 8084
message: Hello from Prod environment!
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/order_prod
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
